# Generated by Django 4.1.7 on 2023-05-12 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='person',
            name='jobtitle',
        ),
    ]
