# Generated by Django 5.1.4 on 2024-12-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0004_remove_person_date_remove_person_departments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(choices=[('Mrs', 'Mrs'), ('Mr', 'Mr')], default='Mr', max_length=3),
        ),
    ]
